### ISSUE TITLE
Backwards compatibility implications of using an existing ID like `'und'` or `'zxx'` for this proposal

### ISSUE THREAD

**Issue by justingrant** [eemeli/proposal-stable-formatting#3]
The locale IDs `und` and `'zxx'` already have existing behavior that would presumably break if the ID for this proposal's locale is `und`. For example: 

```js
new Date().toLocaleDateString('und')
//  => '9/2/2023'. (not '2023-02-09')
```

To avoid breaking existing code with this proposal, should it pick a brand-new ID instead of re-purposing an existing ID?

**Comment by eemeli** [comment]
The behaviour that you're observing is not the `und` locale being supported, but fallback to the host locale due to an unsupported locale identifier. For example, in my `en-FI` environment I get `'02/09/2023'` as the result of the same call.

**Comment by justingrant** [comment]
> The behaviour that you're observing is not the `und` locale being supported, but fallback to the host locale due to an unsupported locale identifier. For example, in my `en-FI` environment I get `'02/09/2023'` as the result of the same call.

Ugh. I guess one of the unfortunate side-effects of Intl's general approach of not throwing with unrecognized options is that if a locale ID is documented and developers use it, then changing its behavior will break them.

IMO this may suggest that it's good to pick an ID that's never been used widely (e.g. because it's documented in MDN or used by TG2 members in public posts)

**Comment by eemeli** [comment]
I was prompted to look a bit deeper, and in the greater JS context I could find two places that do use `und` already:
- Chrome and Node.js do recognise it for `Intl.Locale`:
  ```js
  new Intl.Locale('und').language === undefined
  ```
  That behaviour is different than for unsupported locales like `zxx`, for which `language` is set to the primary subtag.

  Safari does something similar, but a bit surprising:
  ```js
  new Intl.Locale('und').language === 'en'
  new Intl.Locale('und').baseName === 'en-US-u-va-posix'
  ```
- The WebExtensions API used across browsers includes [`tabs.detectLanguage()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/detectLanguage), which may return a promise resolving to `'und'`.
